name: "Report status of a workflow on slack"
description: "Report status of a workflow on slack"
runs:
  using: "node12"
  main: "dist/index.js"

inputs:
  github-run-id:
    description: "GITHUB_RUN_ID"
    required: true
  slack-notify-event:
    description: "SLACK_NOTIFY_EVENT"
    required: true
  commit-message:
    description: "COMMIT_MESSAGE"
    required: false
    default: ""
  webhook-token:
    description: "WEBHOOK_TOKEN"
    required: true
