name: "remove-testing-images"
description: "Remove a testing image by tag or clean up all unneeded images(untagged or with only one commit hash tag)"
runs:
  using: "node20"
  main: "dist/index.js"
inputs:
  GITHUB_TOKEN:
    description: "GitHub token"
    required: true
  PACKAGE_NAME:
    description: "Container name, acceptable values: api-testing, website-testing, crm-testing, lld-testing"
    required: true
  TAG:
    description: "A specific Tag to find and removing the image"
    required: false
