name: "remove-testing-images"
description: "Removes a testing image by tag or clean up all unneeded and old images(older than 3 months)"
runs:
  using: "node20"
  main: "dist/index.js"
inputs:
  github-token:
    description: "GitHub token"
    required: true
  package-name:
    description: "Container name, acceptable values: api-testing, website-testing, crm-testing, lld-testing"
    required: true
  bulk-cleanup:
    description: "Whether the unneeded images should be deleted or not"
    required: true
  tag:
    description: "A specific Tag to find and removing the image"
    required: false
