name: 'slack-check-runs-notify'
description: 'Check if there is a job that has failed for this commit and report it to Slack'
author: 'Wunderflats GmbH'
inputs:
  github-run-id:
    description: "GITHUB_RUN_ID"
    required: true
  commit-message:
    description: "COMMIT_MESSAGE"
    required: false
    default: ""
  webhook-token:
    description: "WEBHOOK_TOKEN"
    required: true
  github-token:
    description: "GITHUB_TOKEN"
    required: true
  failed-message:
    description: "FAILED_MESSAGE"
    required: false
    default: ""
runs:
  using: 'node12'
  main: 'dist/index.js'
