name: "Auto cancel workflow"
description: "Automatically cancel older workflows when a new commit is pushed to the same branch."
author: "Emmanuel Viala"
inputs:
  GITHUB_TOKEN:
    description: "A valid token for listing and cancelling workflows"
    required: true
runs:
  using: "node12"
  main: "main.js"
