name: "cancel-if-not-latest"
description: "Cancel a push workflow if it's not triggered by the latest commit of its branch"
runs:
  using: "node20"
  main: "dist/index.js"
inputs:
  github-token:
    description: "GitHub token"
    required: true
