name: "Build context"
runs:
  using: node16
  main: dist/index.js

inputs:
  registry:
    description: The image registry to use for images that get deployed e.g. ghcr.io
    required: true
  image-name:
    description: The path to append to the registry e.g. wunderflats/my-project
    required: true
  default-branch:
    description: E.g. "main" or "master".
    default: master
    required: false

outputs:
  git-sha:
    description: The git commit SHA that triggered the workflow
  git-branch:
    description: The git branch that triggered the push workflow or PR workflow
  git-branch-escaped:
    description: The git branch, but escaped with dashes
  image-repository:
    description: >
      The repository of the test image, without a tag
      e.g. `ghcr.io/wunderflats/my-project`
  image-sha:
    description: >
      The full name of the image tagged with the git commit SHA
      e.g. `ghcr.io/wunderflats/my-project-testing:abc12345
  image-branch:
    description: >
      The full name of the image tagged with the git branch
      e.g. `ghcr.io/wunderflats/my-project-testing:mybranch`
  image-default-branch:
    description: >
      The full name of the image tagged with the git branch
      e.g. `ghcr.io/wunderflats/my-project-testing:mybranch`
