name: "comment-snyk-report"
description: "Add a comment on the PR with Snyk report"
runs:
  using: "node20"
  main: "dist/index.js"
inputs:
  github-token:
    description: "GitHub token"
    required: true
  dependencies-check-file:
    description: "The path of dependencies check report"
  codebase-check-file:
    description: "The path of codebase check report"
