name: "Prevent concurrent deploy"
description: "Prevent a workflow to run by failing if a previous deployment is still running."
author: "Emmanuel Viala"
inputs:
  GITHUB_TOKEN:
    description: "A valid token for listing workflows"
    required: true
  SKIP_QUEUED_ACTIONS:
    description: "Ignore queued actions (default false)"
    required: false
runs:
  using: "node12"
  main: "main.js"
